# -*- coding: utf-8 -*-
"""CheapFlight.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kv6FaOMVRwISjF_eyubUt6ZUzS4bHp3l
"""

pip install streamlit
import streamlit as st
import pandas as pd

# -------------------------
# Title
# -------------------------
st.title("✈️ Cheapest Flight Finder")

# -------------------------
# Sample dataset (you can replace with your real data / API)
# -------------------------
data = {
    "From": ["New York", "New York", "Boston", "Boston"],
    "To": ["London", "Paris", "London", "Paris"],
    "Price": [500, 450, 480, 430]
}
df = pd.DataFrame(data)

# -------------------------
# User inputs
# -------------------------
from_city = st.selectbox("Select Departure City", df["From"].unique())
to_city = st.selectbox("Select Destination City", df["To"].unique())

# -------------------------
# Show results
# -------------------------
if st.button("Find Cheapest Flight"):
    result = df[(df["From"] == from_city) & (df["To"] == to_city)]
    if not result.empty:
        st.success(f"💲 Cheapest price: ${result['Price'].min()}")
        st.dataframe(result)
    else:
        st.error("No flights found for this route.")
